{% set name = "resolvelib" %}
{% set version = "0.9.0" %}
{% set sha256 = "c491405eaff5278fd6cd3a467de2f6f20b98bbd05254d7283b3b128ee2b305d8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # GitHub release contains tests/
  url: https://github.com/sarugaku/{{ name|lower }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python

test:
  imports:
    - resolvelib
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/sarugaku/resolvelib
  license: ISC
  license_family: OTHER
  license_file: LICENSE
  summary: Simple, fast, extensible JSON encoder/decoder for Python
  description: |
    ResolveLib at the highest level provides a Resolver class that
    includes dependency resolution logic. You give it some things, and a
    little information on how it should interact with them, and it will
    spit out a resolution result.
  doc_url: https://github.com/sarugaku/resolvelib/blob/master/README.rst
  dev_url: https://github.com/sarugaku/resolvelib

extra:
  recipe-maintainers:
    - etcet
